import Image from 'next/image';
import Link from 'next/link';
import logo from '../assets/logo.png';
import './globals.css';

export const metadata = {
  title: 'MCSR Ranked — Advanced Stats',
  description: 'Generated by Next.js',
  icons: {
    icon: logo.src,
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="dark">
      <body>
        <Link
          href="/"
          aria-label="Go to home"
          style={{
            position: 'fixed',
            top: 16,
            left: 16,
            zIndex: 9999,
            display: 'inline-flex',
            alignItems: 'center',
            gap: 8,
            textDecoration: 'none',
          }}
        >
          <Image src={logo} alt="MCSR Ranked" width={48} height={40} priority />
        </Link>
        {children}
      </body>
    </html>
  )
}
